# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);
--insert into people (name, age) values ('Tom Brown', 20);

# --- !Downs

drop table "people" if exists;
